---
title: "Advanced BS Moddeling"
output:
  html_notebook: default
  word_document: default
  pdf_document: default
---


```{r}
#Creating advanced model - plotting as function which varies depending on option type, (call/put) all variables in classic BS Model, then extending to include dividends, transaction fees, and multiple interest rates
# let rx = mean average of total interest rates
rx <- function(n, total){
  rx <- total/n
  rx
}
#Then plug rx value into BS equation
BlackScholesAdv <- function(Type, S, X, Time, rx, sigma, q, tau) {
#Set d1, d2
    d1 <- (log(S/X)+(rx-q+sigma^2/2)*Time)/sigma*sqrt(Time)
    d2 <- d1 - sigma * sqrt(Time)

    if(Type == 'c') {
        P <- S*exp(-q*Time)*pnorm(d1) - X*exp(-rx*Time)*pnorm(d2) - tau
    } else if(Type == 'p') {
        P <- -S*exp(-q*Time)*pnorm(-d1) + X*exp(-rx*Time)*pnorm(-d2) - tau
    }#If type is not call or put, stop executing, alert user to change this
    else {stop("Please only use c or p as Type")}
    P
}
#Set ExpiryValue = Max(ST-X,0)+ for Call and Max(X-ST,0) for Put option
ExpiryValue2 <- function(Type,S,X) {
    op_type = ifelse(Type == 'c', 1, -1)
    max(op_type*(S-X), 0)
}
```

```{r}
#Running example values to show code output, including error handling in BlackScholes Function
BlackScholesAdv('c',110,100,1,0.04,0.2,0.25,1)
BlackScholesAdv('p',110,100,1,0.04,0.2,0.25,1)
ExpiryValue2('c',110,100)
ExpiryValue2('p',110,100)
BlackScholesAdv('s',110,100,1,0.04,0.2,0.25,1)
```

```{r}
#Generate suitable axis, then plot Expiryvalue vs BlackScholes Value
S_range = seq(30, 200, 2)
P = sapply(S_range, function(S) BlackScholesAdv('c', S, 120, 1, .1, .3,.1,.5))
#including just 1% dividend yield majorly increases gradient of expiry payoff and intersects OP as a result
Ex = sapply(S_range, function(S) ExpiryValue2('c', S, 120))
plot(S_range, P, type='l', col='blue', lwd=2, xlab='Spot', ylab='Call Price')
#transaction fees usually small so provides little effect to overall result. In this case shifts OP intercept -.5 units down
lines(S_range, Ex, col='red', lwd=2)
```